# Generated by Django 2.1.7 on 2019-02-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190214_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='contrnt',
            new_name='content',
        ),
    ]
